name: Project Tracking & Notifications

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  project_card:
    types: [created, moved, converted, deleted]
  project:
    types: [created, edited, closed, reopened, deleted]
  project_column:
    types: [created, edited, moved, deleted]
  milestone:
    types: [created, closed, opened, edited, deleted]
  pull_request:
    types: [opened, closed, reopened, edited, assigned, unassigned, review_requested, review_request_removed, labeled, unlabeled, milestoned, demilestoned]

jobs:
  issue_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Send Teams Issue Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Issue Update"
          summary: "Issue ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "${{ github.event.issue.title }}",
              "activitySubtitle": "Issue #${{ github.event.issue.number }} - ${{ github.event.action }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Status",
                  "value": "${{ github.event.issue.state }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Labels",
                  "value": "${{ join(github.event.issue.labels.*.name, ', ') || 'None' }}"
                },
                {
                  "name": "Assignees",
                  "value": "${{ join(github.event.issue.assignees.*.login, ', ') || 'None' }}"
                },
                {
                  "name": "Milestone",
                  "value": "${{ github.event.issue.milestone.title || 'None' }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Issue",
              "targets": [
                { 
                  "os": "default",
                  "uri": "${{ github.event.issue.html_url }}"
                }
              ]
            }]