name: Project Tracking & Notifications

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  project_card:
    types: [created, moved, converted, deleted]
  project:
    types: [created, edited, closed, reopened, deleted]
  project_column:
    types: [created, edited, moved, deleted]
  milestone:
    types: [created, closed, opened, edited, deleted]
  pull_request:
    types: [opened, closed, reopened, edited, assigned, unassigned, review_requested, review_request_removed, labeled, unlabeled, milestoned, demilestoned]

jobs:
  issue_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Send Teams Issue Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Issue Update"
          summary: "Issue ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "${{ github.event.issue.title }}",
              "activitySubtitle": "Issue #${{ github.event.issue.number }} - ${{ github.event.action }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Status",
                  "value": "${{ github.event.issue.state }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Labels",
                  "value": "${{ join(github.event.issue.labels.*.name, ', ') || 'None' }}"
                },
                {
                  "name": "Assignees",
                  "value": "${{ join(github.event.issue.assignees.*.login, ', ') || 'None' }}"
                },
                {
                  "name": "Milestone",
                  "value": "${{ github.event.issue.milestone.title || 'None' }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Issue",
              "targets": [
                { 
                  "os": "default",
                  "uri": "${{ github.event.issue.html_url }}"
                }
              ]
            }]

  comment_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment'
    steps:
      - name: Send Teams Comment Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Issue Comment ${{ github.event.action }}"
          summary: "A comment was ${{ github.event.action }} on an issue in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "${{ github.event.issue.title }}",
              "activitySubtitle": "Issue #${{ github.event.issue.number }} - Comment ${{ github.event.action }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Issue Status",
                  "value": "${{ github.event.issue.state }}"
                },
                {
                  "name": "Comment By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Comment Preview",
                  "value": "${{ github.event.comment.body | slice:0, 100 }}${{ github.event.comment.body.length > 100 && '...' || '' }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Comment",
              "targets": [
                {
                  "os": "default",
                  "uri": "${{ github.event.comment.html_url }}"
                }
              ]
            }]

  project_card_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'project_card'
    steps:
      - name: Send Teams Project Card Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Project Card ${{ github.event.action }}"
          summary: "A project card was ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "Project Card ${{ github.event.action }}",
              "activitySubtitle": "Card ID: ${{ github.event.project_card.id }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Project URL",
                  "value": "${{ github.event.project_card.project_url }}"
                },
                {
                  "name": "Column ID",
                  "value": "${{ github.event.project_card.column_id }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Project Card",
              "targets": [
                {
                  "os": "default", 
                  "uri": "${{ github.event.project_card.url }}"
                }
              ]
            }]

  project_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'project'
    steps:
      - name: Send Teams Project Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Project ${{ github.event.action }}"
          summary: "A project was ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "${{ github.event.project.name }}",
              "activitySubtitle": "Project ${{ github.event.action }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Project Body",
                  "value": "${{ github.event.project.body || 'No description' }}"
                },
                {
                  "name": "Project State",
                  "value": "${{ github.event.project.state }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Project",
              "targets": [
                {
                  "os": "default", 
                  "uri": "${{ github.event.project.html_url }}"
                }
              ]
            }]

  column_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'project_column'
    steps:
      - name: Send Teams Column Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Project Column ${{ github.event.action }}"
          summary: "A project column was ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "Project Column ${{ github.event.action }}",
              "activitySubtitle": "Column ID: ${{ github.event.project_column.id }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Column Name",
                  "value": "${{ github.event.project_column.name }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Project",
              "targets": [
                {
                  "os": "default", 
                  "uri": "${{ github.event.project_column.project_url }}"
                }
              ]
            }]

  milestone_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'milestone'
    steps:
      - name: Send Teams Milestone Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Milestone ${{ github.event.action }}"
          summary: "A milestone was ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "${{ github.event.milestone.title }}",
              "activitySubtitle": "Milestone ${{ github.event.action }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Description",
                  "value": "${{ github.event.milestone.description || 'No description' }}"
                },
                {
                  "name": "State",
                  "value": "${{ github.event.milestone.state }}"
                },
                {
                  "name": "Due Date",
                  "value": "${{ github.event.milestone.due_on || 'No due date' }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Milestone",
              "targets": [
                {
                  "os": "default", 
                  "uri": "${{ github.event.milestone.html_url }}"
                }
              ]
            }]

  pull_request_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Send Teams Pull Request Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_url: ${{ secrets.UPDATE_ON_PROJECT_STATUS }}
          title: "Pull Request ${{ github.event.action }}"
          summary: "A pull request was ${{ github.event.action }} in ${{ github.repository }}"
          sections: |
            [{
              "activityTitle": "${{ github.event.pull_request.title }}",
              "activitySubtitle": "PR #${{ github.event.pull_request.number }} - ${{ github.event.action }}",
              "activityImage": "${{ github.event.sender.avatar_url }}",
              "facts": [
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Status",
                  "value": "${{ github.event.pull_request.state }}"
                },
                {
                  "name": "Action",
                  "value": "${{ github.event.action }}"
                },
                {
                  "name": "Author",
                  "value": "${{ github.event.pull_request.user.login }}"
                },
                {
                  "name": "Triggered By",
                  "value": "${{ github.actor }}"
                },
                {
                  "name": "Labels",
                  "value": "${{ join(github.event.pull_request.labels.*.name, ', ') || 'None' }}"
                },
                {
                  "name": "Milestone",
                  "value": "${{ github.event.pull_request.milestone.title || 'None' }}"
                }
              ],
              "markdown": true
            }]
          actions: |
            [{
              "@type": "OpenUri",
              "name": "View Pull Request",
              "targets": [
                { 
                  "os": "default",
                  "uri": "${{ github.event.pull_request.html_url }}"
                }
              ]
            }]